### ISSUE TITLE
Doesn't play nicely with null values or the HasJsonWrapper trait

### ISSUE THREAD

**Issue by curtisblackwell** [dcasia/nova-json-wrapper#2]
To get this working, I had to:

- Override the `getOriginal` method on my model and
- **not** use the `HasJsonWrapper` trait the docs say to use.

My model:
```php
class Client extends Model
{
    protected $casts = [ 'contact_phone' => 'array'];

    public function getOriginal($key = null, $default = null)
    {
        return $key === 'contact_phone'
            ? parent::getOriginal($key, $default) ?? '[]'
            : parent::getOriginal($key, $default);
    }
}
```

This is because `JsonWrapper.php:103` has `json_decode($model->getOriginal($this->attribute), true)`, which messes up when the attribute value is `null`. This could be fixed by replacing it with `json_decode($model->getOriginal($this->attribute) ?? '[]', true)`.

As for the `HasJsonWrapper` trait, the only effect I'm noticing is that it hides my fields for some reason. Just leaving it off works just fine.

**Comment by milewski** [comment]
Hi @curtisblackwell , I fixed the problem with the `getOriginal` and the trait on version [v0.1.3](https://github.com/dcasia/nova-json-wrapper/releases/tag/v0.1.3)

The `HasJsonWrapper` is required in order to display the fields correctly within your details view page, without it all your JSON fields will just disappear from details view

**Comment by curtisblackwell** [comment]
Awesome, thanks for the quick update!
